import { useCopy, type Lang } from "../../i18n";

/** The Reader's own words (buttons, labels, small print), in both languages. The content files hold everything else. */
const UI = {
  en: {
    close: "Close",
    prevPage: "Previous page",
    nextPage: "Next page",
    chapters: "Chapters",
    nextCase: "Next case →",
    sayHello: "Say hello",
    theEnd: "The end",
    thanks: "Thanks for reading",
    prototype: "Prototype",
    openPrototype: "Open the prototype",
    jumpToScreen: "Jump to a screen",
    screens: "Screens",
    chooseVersion: "Choose a version",
    winner: "Winner",
    now: "Now",
    pickToSee: "Pick one to see the answer.",
    yourPick: "Your pick",
    right: "Right!",
    notQuite: "Not quite.",
    tryAgain: "Try again",
    prevQuote: "Previous quote",
    nextQuote: "Next quote",
    choosePersona: "Choose a persona",
    traits: "Traits",
    behavior: "Behavior",
    context: "Context",
    needs: "Needs",
    whoseJourney: "Whose journey",
    howItFeels: "How it feels. ",
    whatTheyDo: (who: string): string => `What ${who} does. `,
    mood: (n: number): string => `mood ${n} of 5`,
    enlarge: "enlarge",
    enlarged: "enlarged",
    enlargeImages: (n: number): string => (n > 1 ? "Enlarge images" : "Enlarge image"),
    photo: "Photo",
    screenN: (n: number): string => `screen ${n}`,
    pageOf: (i: number, n: number): string => `Page ${i} of ${n}`,
    theEndShort: "the end",
    noteOf: (i: number, n: number): string => `Note ${i} of ${n}`,
    dragToTurn: "Drag to turn it",
    continued: " · continued",
    resumeSections: { Profile: "Profile", Experience: "Experience", Education: "Education", Skills: "Skills", Languages: "Languages", "What people say": "What people say" } as Record<string, string>,
    prevResume: "Previous page of the résumé",
    nextResume: "Next page of the résumé",
    alwaysLearning: "Always learning",
    courses: "Courses and specializations",
    swipe: "Swipe",
    /** Under a note shown in the other language from the one it was written in. */
    translated: "Translated from Portuguese",
    prevNote: "Previous note",
    nextNote: "Next note",
    countriesGoal: (goal: number): string => ` of my ${goal}-country goal`,
    countriesGoalLabel: "Countries visited toward my goal",
    countriesList: "Countries I've visited",
    dropCoin: "Drop a coin in the llama bank",
    coinsToward: "Coins toward the next milestone",
    coins: (n: number): string => (n === 1 ? "coin" : "coins"),
    toYou: "To: you,",
    readingThis: "reading this",
    seeFront: "See the front",
    turnOver: "Turn over",
    chessTiles: { Blitz: "Blitz", Rapid: "Rapid", Daily: "Daily", Puzzles: "Puzzles" } as Record<string, string>,
    best: "best",
    chessRatings: "My chess.com ratings",
    chessJoke: (kind: string, best: number, current: number): string => `Best ${kind}: ${best}. Current: ${current}. We don't talk about it.`,
    phoneHint: "Tap a number and the phone dials it for you. Or spin the dial yourself.",
    writeEmail: "Write an email",
    open: (label: string): string => `Open ${label}`,
    copied: "Copied!",
    dialling: (d: string): string => `Dialling ${d}…`,
    ringing: (d: string): string => `Calling ${d}… ring, ring`,
    copyAddress: "Copy address",
    phoneHintDesk: (keys: string): string => `Pick a number and the phone dials it for you (or press ${keys}). You can spin the dial yourself, too.`,
    or: "or",
    aNumber: "a number",
    nextMilestone: (n: number): string => ` · next milestone at ${n}`,
    allMilestones: " · every milestone reached",
    zukoKnows: "Questions Zuko knows",
    yourQuestion: "Your question",
    ask: "Ask",
  },
  pt: {
    close: "Fechar",
    prevPage: "Página anterior",
    nextPage: "Próxima página",
    chapters: "Capítulos",
    nextCase: "Próximo case →",
    sayHello: "Vamos conversar?",
    theEnd: "Fim",
    thanks: "Obrigada por ler até aqui",
    prototype: "Protótipo",
    openPrototype: "Abrir o protótipo",
    jumpToScreen: "Ir para uma tela",
    screens: "Telas",
    chooseVersion: "Escolha uma versão",
    winner: "Vencedora",
    now: "Hoje",
    pickToSee: "Escolha uma opção para ver a resposta.",
    yourPick: "Sua escolha",
    right: "Isso!",
    notQuite: "Não foi dessa vez.",
    tryAgain: "Tentar de novo",
    prevQuote: "Citação anterior",
    nextQuote: "Próxima citação",
    choosePersona: "Escolha uma persona",
    traits: "Características",
    behavior: "Comportamento",
    context: "Contexto",
    needs: "Necessidades",
    whoseJourney: "Jornada de quem",
    howItFeels: "Como se sente. ",
    whatTheyDo: (who: string): string => `O que ${who === "Lucas" ? "o" : "a"} ${who} faz. `,
    mood: (n: number): string => `humor ${n} de 5`,
    enlarge: "ampliar",
    enlarged: "ampliada",
    enlargeImages: (n: number): string => (n > 1 ? "Ampliar imagens" : "Ampliar imagem"),
    photo: "Foto",
    screenN: (n: number): string => `tela ${n}`,
    pageOf: (i: number, n: number): string => `Página ${i} de ${n}`,
    theEndShort: "fim",
    noteOf: (i: number, n: number): string => `Bilhete ${i} de ${n}`,
    dragToTurn: "Arraste para girar",
    continued: " · continuação",
    resumeSections: { Profile: "Perfil", Experience: "Experiência", Education: "Formação", Skills: "Habilidades", Languages: "Idiomas", "What people say": "O que dizem" } as Record<string, string>,
    prevResume: "Página anterior do currículo",
    nextResume: "Próxima página do currículo",
    alwaysLearning: "Sempre aprendendo",
    courses: "Cursos e especializações",
    swipe: "Deslize",
    translated: "Traduzido do inglês",
    prevNote: "Bilhete anterior",
    nextNote: "Próximo bilhete",
    countriesGoal: (goal: number): string => ` da minha meta de ${goal} países`,
    countriesGoalLabel: "Países visitados rumo à minha meta",
    countriesList: "Países que já visitei",
    dropCoin: "Dar uma moeda para a lhama",
    coinsToward: "Moedas até a próxima meta",
    coins: (n: number): string => (n === 1 ? "moeda" : "moedas"),
    toYou: "Para: você,",
    readingThis: "que está lendo isto",
    seeFront: "Ver a frente",
    turnOver: "Virar",
    chessTiles: { Blitz: "Blitz", Rapid: "Rápida", Daily: "Diária", Puzzles: "Problemas" } as Record<string, string>,
    best: "melhor",
    chessRatings: "Meus ratings no chess.com",
    chessJoke: (kind: string, best: number, current: number): string => `Melhor rating de ${kind}: ${best}. Atual: ${current}. Melhor nem comentar.`,
    phoneHint: "Toque num número e o telefone disca sozinho. Ou gire o disco, se preferir.",
    writeEmail: "Escrever um email",
    open: (label: string): string => `Abrir ${label}`,
    copied: "Copiado!",
    dialling: (d: string): string => `Discando ${d}…`,
    ringing: (d: string): string => `Chamando ${d}… trim, trim`,
    copyAddress: "Copiar endereço",
    phoneHintDesk: (keys: string): string => `Escolha um número e o telefone disca sozinho (ou aperte ${keys}). Dá para girar o disco também.`,
    or: "ou",
    aNumber: "um número",
    nextMilestone: (n: number): string => ` · próxima meta: ${n}`,
    allMilestones: " · todas as metas batidas",
    zukoKnows: "Perguntas que o Zuko sabe",
    yourQuestion: "Sua pergunta",
    ask: "Enviar",
  },
} satisfies Record<Lang, unknown>;

export type ReaderUi = (typeof UI)["en"];

export function useUi(): ReaderUi {
  return useCopy<ReaderUi>(UI);
}
